CREATE DATABASE ECOM;
USE ECOM;

CREATE TABLE USERS(
USERNAME VARCHAR(30) PRIMARY KEY,
FULLNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
MOBILE VARCHAR(13),
PASSWORD VARCHAR(20) NOT NULL
);
INSERT INTO USERS VALUES("MAHITHA","N.MAHITHA","nuthakkimahitha16@gmail.com","7794909382","mahitha");
SELECT * FROM USERS;

CREATE TABLE CART(
CART_ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(20) NOT NULL,
PRODUCT_ID INT NOT NULL,
PRODUCT_NAME VARCHAR(30) NOT NULL,
PRODUCT_PRICE INT NOT NULL,
QUANTITY INT NOT NULL DEFAULT 1,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
SELECT * FROM CART;
truncate cart;

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USERNAME VARCHAR(20) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    QUANTITY INT NOT NULL
);
SELECT * FROM ORDERS;
INSERT INTO ORDERS (USERNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY)
SELECT (USERNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY) FROM CART;
