CREATE DATABASE ECOM;
USE ECOM;
CREATE TABLE USERS(
USERNAME VARCHAR(30) PRIMARY KEY,
FULLNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
MOBILE VARCHAR(13),
PASSWORD VARCHAR(20) NOT NULL
);
INSERT INTO USERS VALUES ("VAMSHI132","K VAMSHI","VAMSHI19100@GMAIL.COM","9390091863","109109KV");
SELECT * FROM USERS;

CREATE TABLE CART(
    CART_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(40) NOT NULL,
    PRODUCT_PRICE VARCHAR(40) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
select * from cart;

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY default 1,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USERNAME VARCHAR(20) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    QUANTITY INT NOT NULL
);
SELECT * FROM ORDERS;